# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='\u7248\u672c\u53f7')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u8bf4\u660e')),
                ('version_update_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7248\u672c\u5347\u7ea7\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-version_update_time'],
                'verbose_name': '\u7248\u672c',
                'verbose_name_plural': '\u7248\u672c',
            },
        ),
    ]
