# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifyRecord',
            new_name='EmailVerificationCode',
        ),
    ]
