# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170305_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bf4\u660e'),
        ),
    ]
