# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170306_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.IntegerField(default=99, verbose_name='\u663e\u793a\u987a\u5e8f'),
        ),
    ]
