# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carousel_jump_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-update_time'], 'verbose_name': '\u4ea7\u54c1\u9879\u76ee', 'verbose_name_plural': '\u4ea7\u54c1\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='prototype',
            options={'ordering': ['-update_time'], 'verbose_name': '\u4ea7\u54c1\u539f\u578b', 'verbose_name_plural': '\u4ea7\u54c1\u539f\u578b'},
        ),
    ]
